fragment eventFields on Events {
  location
  bookmarks_count
  city {
    name
    id
  }
  date
  description
  id
  images
  price
  specificAddress
  tags
  title
  user {
    avatarUrl
    description
    email
    followers_count
    id
    name
  }
  bookmarked_by_user
  followed_by_user
}
