export { default as getEventByLocationQuery } from "./get-events-by-location.query.gql"
export { default as getEventQuery } from "./get-event.query.gql"
export { default as searchEventsQuery } from "./search-events.query.gql"
export { default as getEventsQuery } from "./get-events.query.gql"
export { default as getMyEventsQuery } from "./get-my-events.query.gql"
export { default as getSavedEventsQuery } from "./get-saved-events.query.gql"